keys:
  - &users:
    - &jakobe age13garmejyv5uf29qqkstwv0xxv27ydnfj04akgygmkwhdy9fdjchqgslc69
  - &hosts:
    - &legion age1av32s3h9jy0mh7d7rfgrksg3eh94259vrc4cyhmm04mk5g4t3c2qcw2ve9

creation_rules:
  - path-regex: secrets.yaml$
    key_groups:
      - age:
          - *jakobe
          - *legion
