keys:
  - &users:
    - &jakobe age13garmejyv5uf29qqkstwv0xxv27ydnfj04akgygmkwhdy9fdjchqgslc69
  - &hosts:
    - &legion age1av32s3h9jy0mh7d7rfgrksg3eh94259vrc4cyhmm04mk5g4t3c2qcw2ve9
    - &servox age12tmx2yd4n67rywh2uv2sytd440vuave36ven62yej5aaqwv8us7sk3d8rv
    - &think age1dfhvh73szhsertym4hsq9pqy82m8976zpu6t07uh44j5936na93qp5ltze

creation_rules:
  - path-regex: secrets.yaml$
    key_groups:
      - age:
          - *jakobe
          - *legion
          - *servox
          - *think
