keys:
  - &standalone age13garmejyv5uf29qqkstwv0xxv27ydnfj04akgygmkwhdy9fdjchqgslc69
  - &think age1l745y2dgr9yn8kxflzyxgssu9s83ysqyx9aszvcvzxr7esh0hpkql5mv03

creation_rules:
  - path-regex: secrets.yaml$
    key_groups:
      - age:
          - *standalone
          - *think
