# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ollama" = {
    image = "ollama/ollama:rocm";
    volumes = [
      "/home/jakobe/docker/ollama:/root/.ollama:rw"
    ];
    ports = [
      "11434:11434/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=/dev/kfd:/dev/kfd:rwm"
      "--network-alias=ollama"
      "--network=ollama_default"
    ];
  };
  systemd.services."docker-ollama" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ollama_default.service"
    ];
    requires = [
      "docker-network-ollama_default.service"
    ];
    partOf = [
      "docker-compose-ollama-root.target"
    ];
    wantedBy = [
      "docker-compose-ollama-root.target"
    ];
  };
  virtualisation.oci-containers.containers."webui" = {
    image = "ghcr.io/open-webui/open-webui:main";
    environment = {
      "OLLAMA_BASE_URL" = "http://ollama:11434";
    };
    volumes = [
      "/home/jakobe/docker/webui:/app/backend/data:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    dependsOn = [
      "ollama"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=webui"
      "--network=ollama_default"
    ];
  };
  systemd.services."docker-webui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ollama_default.service"
    ];
    requires = [
      "docker-network-ollama_default.service"
    ];
    partOf = [
      "docker-compose-ollama-root.target"
    ];
    wantedBy = [
      "docker-compose-ollama-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ollama_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ollama_default";
    };
    script = ''
      docker network inspect ollama_default || docker network create ollama_default
    '';
    partOf = [ "docker-compose-ollama-root.target" ];
    wantedBy = [ "docker-compose-ollama-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ollama-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
