name: "ollama"
services:
  webui:
    container_name: webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080/tcp
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./webui:/app/backend/data
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    ports:
      - 11434:11434/tcp
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
