#!/usr/bin/env bash
xrandr --output eDP-1 --mode 2560x1600 --pos 0x0 --rotate normal --output DP-1-0 --primary --rate 164.83  --mode 2560x1440 --pos 2560x80 --rotate normal --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off --output HDMI-1-0 --off --output DP-1-4 --off


xrandr --output eDP-1 --mode 2560x1600 --pos 0x0 --rotate normal --output DP-1-2 --primary --rate 164.83  --mode 2560x1440 --pos 2560x80 --rotate normal --output DP-1-1 --off --output DP-1-0 --off --output DP-1-3 --off --output HDMI-1-0 --off --output DP-1-4 --off
